language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php: 
 - 5.6
 - 7.0

addons:
  postgresql: "9.3"

env: 
  - MOODLE_BRANCH=master DB=mysqli IGNORE_PATHS=jquery
#  - MOODLE_BRANCH=master DB=pgsql IGNORE_PATHS=jquery

  
  

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci shifter
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat