version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "php"
      - dependency-name: "moodlehq/moodle-cs"
        update-types: ["version-update:semver-major"]
