language: php

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  global:
    # Copy/paste from XMLDBEditor should not be linted.
    # Custom form elements are formatted according for formslib, which doesn't match Moodle's style.
    - IGNORE_PATHS=db/upgrade.php,classes/form/duration.php,classes/form/itemspertime.php

  matrix:
    - MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_310_STABLE DB=mysqli
    - MOODLE_BRANCH=master DB=pgsql

matrix:
  exclude:
    # Exclude builds not compatible with 7.0.
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=mysqli
    - php: 7.0
      env: MOODLE_BRANCH=master DB=pgsql

    # Exclude builds not compatible with 7.1.
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=master DB=pgsql

    # Exclude builds not compatible with 7.2.
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql

    # Exclude builds not compatible with 7.3.
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql

    # Exclude builds not compatible with 7.4.
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

  # The following plugins are disabled:
  # - moodle-plugin-ci phpmd
  # - moodle-plugin-ci phpcpd
  # - moodle-plugin-ci phpdoc
  #
  # This one complains too much about CSS and YUI linting...
  # - moodle-plugin-ci grunt
