language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.4

env:
  global:
    # Copy/paste from XMLDBEditor should not be linted.
    # Custom form elements are formatted according for formslib, which doesn't match Moodle's style.
    - IGNORE_PATHS=db/upgrade.php,classes/form/duration.php,classes/form/itemspertime.php

  matrix:
    # Temporary ignore the following due to incompatibilities.
    # - MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - MOODLE_BRANCH=master DB=pgsql

matrix:
  exclude:
    # Exclude builds not compatible with 5.4.
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 5.4
      env: MOODLE_BRANCH=master DB=pgsql

    # Exclude builds not compatible with 5.6.
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 5.6
      env: MOODLE_BRANCH=master DB=pgsql

    # Exclude builds not compatible with 7.0.
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.0
      env: MOODLE_BRANCH=master DB=pgsql

    # Exclude builds not compatible with 7.1.
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql

    # Exclude builds not compatible with 7.2.
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql

    # Exclude builds not compatible with 7.3.
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

  # The following plugins are disabled:
  # - moodle-plugin-ci phpmd
  # - moodle-plugin-ci phpcpd
  # - moodle-plugin-ci phpdoc
  #
  # This one complains too much about CSS and YUI linting...
  # - moodle-plugin-ci grunt
