language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.1
 - 7.2

services:
 - mysql
 - postgresql

env:
 global:
  - IGNORE_PATHS=sdk/,fonts/,pix/
  - IGNORE_NAMES=jquery*,moment.js,colorbox.css,tooltipster.css,*.min.css,*.min.js,tii-icon-webfont.css,styles.css,styles.css.map,gulpfile.js
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
 - moodle-plugin-ci phplint
 - moodle-plugin-ci phpmd
 - moodle-plugin-ci csslint
 - moodle-plugin-ci shifter
 - moodle-plugin-ci validate
 - moodle-plugin-ci phpunit